site_name: Rango Test
# site_url: 
site_author: Rango
# 代码仓库信息
repo_name: rangoljx/rango-web # 仓库名称
repo_url: https://github.com/rangoljx/rango-web.git/ # 仓库地址
theme:
  name: material
  language: en # 默认语言
  keyboard: #配置搜索快捷键
    search: s, /
  # icon:
  #   logo: material/book-open-page-variant  # 网站 Logo
  #   repo: fontawesome/brands/github        # 仓库图标
  # favicon: assets/favicon.png              # 网站图标
  palette:
    # 可用的主题色：
    # red, pink, purple, deep purple, indigo, blue, light blue, 
    # cyan, teal, green, light green, lime, yellow, amber, 
    # orange, deep orange, brown, grey, blue grey
    - scheme: default # 日间模式
      primary: blue grey # # 主色调
      accent: light green # 链接等可交互元件的高亮色# 强调色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: pink
      toggle:
        icon: material/weather-sunny
  font:
    text: Roboto
    code: Roboto Mono
  icon: # 一些用到的icon
    repo: simple/github
    edit: material/pencil-box-multiple
    view: material/eye
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code
  features:
  - navigation.instant #- header.autohide  #自动隐藏
  - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
  - navigation.tabs.sticky #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
  - navigation.sections
  - navigation.top   # 返回顶部的按钮 在上滑时出现
  - navigation.indexs #使用目录索引
  - navigation.footer  # 启用页脚
  # - toc.integrate      # 集成目录于左边
  # - navigation.expand #打开默认展开子菜单

  # 搜索主题配置
  - search.suggest # 启用搜索建议
  - search.highlight # 搜索出的文章关键词加入高亮
  - search.share   #搜索分享按钮

  - content.code.annotate # 启用代码注释
  - content.code.copy    # 启用代码复制
  - content.action.edit  # 页面编辑图标
  - content.action.view  # 页面编辑图标
  # hide:
  # # - navigation # Hide navigation
  # - toc        # Hide table of contents

plugins:
  - search: #默认插件
      # 搜索索引设置  
      lang: 
        - en
        - zh
      separator: '[\s\-\.]+' # 分词分隔符
      min_search_length: 2 # 最小搜索长度
      prebuild_index: ture  # 预构建索引
      # 搜索内容配置
      indexing:
        full_sections: true       # 索引完整章节
        headings: true           # 索引标题
        content: true           # 索引内容
        tags: true             # 索引标签
      # 搜索结果排序
      scoring:
        title_boost: 10        # 标题权重
        heading_boost: 5       # 标题权重
        content_boost: 1       # 内容权重

  - i18n: # 多语言插件
      docs_structure: suffix # 抄来的，不太懂
      fallback_to_default: true # 抄来的，不太懂
      reconfigure_material: true # 抄来的，不太懂
      reconfigure_search: true # 抄来的，不太懂
      languages: # 多语言配置 - 需要小心一点
        - locale: en
          default: true # 默认语言
          name: English
          build: true # 是否构建
          # site_name: Infinity
        - locale: zh
          name: 简体中文
          build: true
          nav_translations: # 导航栏翻译，不可以有缩进
            HOME: 首页
            ABOUT: 关于
            TAGS: 标签
            python3 programming: python3编程


  # 标签系统pip install mkdocs-tags-plugin
  - tags:
      tags_file: tags.md #标签
      tags_allowed:  # 允许的标签列表
        - Python
        - JavaScript
        - CSS
        - HTML
        - Linux
      tags_extra_files:
        cloud: tag_cloud.md    # 标签云页面
        list: tag_list.md      # 标签列表页面

  # 统计分析
  - statistics:
      page_statistics: True #是否在单页中显示统计信息
      page_read_time: True #是否显示单页预计阅读时间
      page_images: True #是否显示单页图片张数
      page_check_metadata: #如果为空，则所有页面都显示；否则包含指定 metadata 才显示单页统计信息

  # 图片预览插件pip install mkdocs-glightbox
  - glightbox:
      # 基础设置
      auto_caption: true              # 自动添加标题
      caption_position: bottom        # 标题位置
      display_description: true       # 显示描述
      # 触摸设置
      touchNavigation: true          # 触摸导航
      loop: true                    # 循环浏览
      effect: zoom                  # 过渡效果
      # 图片设置
      width: 100%                   # 图片宽度
      height: auto                  # 图片高度
      zoomable: true               # 启用缩放
      draggable: true              # 启用拖动
  - blog

# 导航设置
nav: 
  - HOME: index.md
  - Python3编程:
    - 入门基础:
      - 环境与安装:
        - 安装Python3: python/basics/install-python3.md
      - 基本语法:
        - 变量与常量: python/basics/variables-constants.md
        - 数据类型:
          - 数字类型: python/basics/data-types/numeric-types.md
          - 字符串类型: python/basics/data-types/string-types.md
          - 列表与元组: python/basics/data-types/lists-tuples.md
          - 字典与集合: python/basics/data-types/dictionaries-sets.md
      - 控制结构:
        - 条件语句: python/basics/control-structures/conditional-statements.md
        - 循环结构: python/basics/control-structures/loop-structures.md
      - 函数与模块:
        - 定义与调用函数: python/basics/functions-modules/define-call-functions.md
        - 导入与使用模块: python/basics/functions-modules/import-use-modules.md
    - 进阶技巧:
      - 推导式:
        - 列表推导式: python/advanced/list-comprehensions.md
        - 字典推导式与集合推导式: python/advanced/dictionary-set-comprehensions.md
      - 迭代器、生成器与协程:
        - 迭代器与可迭代对象: python/advanced/iterators-iterables.md
        - 生成器函数与表达式: python/advanced/generators-functions-expressions.md
        - 协程与异步编程: python/advanced/coroutines-async-programming.md
      - 装饰器与元类:
        - 装饰器基础与应用: python/advanced/decorators-basics-applications.md
        - 元类与自定义类创建: python/advanced/metaclasses-custom-class-creation.md
    - Python3特性:
      - 新增功能:
        - Python3专属语法与特性: python/python3-features/python3-syntax-features.md
        - 类型注解与类型提示: python/python3-features/type-annotations-hints.md
      - 与Python2的差异:
        - 语法与标准库差异: python/python3-features/python2-vs-python3-differences.md
      - 淘汰内容:
        - 淘汰的特性与模块: python/python3-features/deprecated-features-modules.md
    - 实战应用:
      - 数据处理与分析:
        - 使用Pandas进行数据分析: python/practical/data-processing-analysis/pandas.md
      - 网络爬虫:
        - Requests与Beautiful Soup实战: python/practical/web-scraping/requests-beautifulsoup.md
      - Web开发基础:
        - Flask/Django框架简介: python/practical/web-development/flask-django-introduction.md

  - MySQL数据库:
    - MySQL简介: mysql/basics.md

    - 数据定义语言 (DDL):
      - 创建与管理数据库: mysql/ddl/create-manage-db.md
      - 表结构定义: mysql/ddl/table-structure.md
      - 索引创建与管理: mysql/ddl/index-management.md
      - 视图与存储过程: mysql/ddl/views-stored-procedures.md

    - 数据操作语言 (DML):
      - 数据插入: mysql/dml/insert-data.md
      - 数据更新: mysql/dml/update-data.md
      - 数据删除: mysql/dml/delete-data.md

    - 数据查询语言 (DQL):
      - 基本查询: mysql/dql/basic-queries.md
      - 条件查询: mysql/dql/conditional-queries.md
      - 排序与分组: mysql/dql/sorting-grouping.md
      - 聚合函数与分页: mysql/dql/aggregate-functions-pagination.md
      - 连接查询: mysql/dql/join-queries.md

    - 数据控制语言 (DCL):
      - 用户与权限管理: mysql/dcl/user-permissions.md
      - 角色与权限分配: mysql/dcl/roles-permissions.md
      - 权限审计与监控: mysql/dcl/audit-monitoring.md

    - 高级功能与优化:
      - 事务处理: mysql/advanced/transactions.md
      - 备份与恢复: mysql/advanced/backup-restore.md
      - 性能调优: mysql/advanced/performance-tuning.md
      - 复制与集群: mysql/advanced/replication-clustering.md

  - Linux学习路线:
    - 入门基础:
      - 简介安装: linux/intro-install.md
      - 命令行: linux/command-line.md
      - 文件管理: linux/file-management.md
      - 用户权限: linux/user-permissions.md
    - 进阶技巧:
      - Shell脚本: linux/shell-scripting.md
      - 包管理: linux/package-mgmt.md
      - 网络服务: linux/network-services.md
      - 进程监控: linux/process-monitor.md
    - 高级应用:
      - 文件系统: linux/filesystem.md
      - 性能优化: linux/performance-opt.md
      - 安全配置: linux/security-config.md
      - 服务器管理: linux/server-mgmt.md
    - 实战项目:
      - 开源参与: linux/open-source.md
      - 个人博客: linux/personal-blog.md
      - 企业部署: linux/enterprise-deploy.md
    - 虚拟机与安装:
      - VMWare虚拟机基础: linux/vmware-basics.md
      - 在VMWare中安装Ubuntu: linux/vmware-install-ubuntu.md
      - Ubuntu物理机安装指南: linux/ubuntu-physical-install.md

  - 软件测试:
    - 测试基础:
      - 测试概念与重要性: testing/basics/test-concepts-importance.md
      - 测试类型与级别: testing/basics/test-types-levels.md
      - 测试计划与策略: testing/basics/test-plans-strategies.md
      - 缺陷管理与报告: testing/basics/defect-management-reporting.md
    - 接口测试:
      - REST API测试基础: testing/api-testing/rest-api-testing-basics.md
      - SOAP API测试指南: testing/api-testing/soap-api-testing-guide.md
      - Postman与SoapUI工具使用: testing/api-testing/postman-soapui-tools.md
      - 接口测试案例与实践: testing/api-testing/test-cases-practices.md
    - 性能测试:
      - 性能测试基础: testing/performance-testing/basics.md
      - 负载测试与压力测试: testing/performance-testing/load-stress-testing.md
      - 响应时间分析: testing/performance-testing/response-time-analysis.md
      - 性能调优与瓶颈识别: testing/performance-testing/tuning-bottleneck-identification.md
    - 自动化测试:
      - 自动化测试基础: testing/automation/basics.md
      - Selenium WebDriver使用: testing/automation/selenium-webdriver.md
      - Appium移动测试框架: testing/automation/appium-mobile-testing.md
      - 持续集成与CI/CD: testing/automation/continuous-integration-cicd.md
      - 自动化测试脚本编写与维护: testing/automation/script-writing-maintenance.md
    - TDD与BDD:
      - 测试驱动开发(TDD): testing/tdd-bdd/tdd.md
      - 行为驱动开发(BDD): testing/tdd-bdd/bdd.md
      - 编写可测试的代码: testing/tdd-bdd/writable-test-code.md
      - Cucumber与SpecFlow工具使用: testing/tdd-bdd/cucumber-specflow-tools.md

  - 问题与解决方案 (Q&A):
    - 编程语言:
      - Python常见问题: qa/programming-languages/python-questions.md
      - JavaScript疑难解答: qa/programming-languages/javascript-answers.md
      - Java编程挑战: qa/programming-languages/java-challenges.md
    - Web开发:
      - 前端开发技巧: qa/web-development/frontend-tips.md
      - 后端服务搭建: qa/web-development/backend-setup.md
      - 数据库优化策略: qa/web-development/database-optimization.md
    - 系统运维:
      - Linux系统管理: qa/system-operations/linux-management.md
      - Windows服务器配置: qa/system-operations/windows-server-config.md
      - 网络故障排查: qa/system-operations/network-troubleshooting.md
    - 数据分析:
      - 数据清洗与处理: qa/data-analysis/data-cleaning-processing.md
      - 数据可视化技巧: qa/data-analysis/data-visualization-tips.md
      - 统计分析与建模: qa/data-analysis/statistical-analysis-modeling.md
    - 人工智能与机器学习:
      - 算法原理与应用: qa/ai-machine-learning/algorithm-principles-applications.md
      - 模型训练与优化: qa/ai-machine-learning/model-training-optimization.md
      - 深度学习框架使用: qa/ai-machine-learning/deep-learning-frameworks.md
    - 软件开发工具:
      - IDE使用技巧: qa/software-development-tools/ide-tips.md
      - 版本控制实践: qa/software-development-tools/version-control-practices.md
      - 构建与部署流程: qa/software-development-tools/build-deployment-processes.md
    - 安全与隐私:
      - 系统安全防护: qa/security-privacy/system-security.md
      - 数据加密技术: qa/security-privacy/data-encryption.md
      - 隐私保护策略: qa/security-privacy/privacy-protection-strategies.md

  - 工具&软件相关:
    - 开发工具:
      - VS Code: tools/development/vscode.md
      - PyCharm: tools/development/pycharm.md
      - IntelliJ IDEA: tools/development/intellij-idea.md
    - 版本控制:
      - Git: tools/version-control/git.md
      - SVN: tools/version-control/svn.md
    - 虚拟机与容器:
      - VMware: tools/virtual-machines/vmware.md
      - Docker: tools/containers/docker.md
      - Kubernetes: tools/containers/kubernetes.md
    - 数据库管理:
      - Navicat: tools/database-management/navicat.md
      - MySQL Workbench: tools/database-management/mysql-workbench.md
    - 网络与通信:
      - Wireshark: tools/network-communication/wireshark.md
      - Fiddler: tools/network-communication/fiddler.md
    - 测试工具:
      - JMeter: tools/testing/jmeter.md
      - Postman: tools/testing/postman.md
      - Selenium: tools/testing/selenium.md
      - Robot Framework: tools/testing/robot-framework.md
    - 持续集成与部署:
      - Jenkins: tools/ci-cd/jenkins.md
      - GitLab CI/CD: tools/ci-cd/gitlab-ci-cd.md
      - Travis CI: tools/ci-cd/travis-ci.md
    - 其他工具:
      - Notepad++: tools/other/notepad-plus-plus.md
      - Sublime Text: tools/other/sublime-text.md
      - Evernote: tools/other/evernote.md

  - 学习资源与工具: resources/index.md
  - 标签: tags.md
  - 总结: about.md

copyright: Copyright &copy; 2024 Rango 
#  Powered by MkDocs with theme Material modified by Rango

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  # 社交链接
  social:
    - icon: material/github
      link: https://github.com/username
      name: GitHub
    - icon: material/twitter
      link: https://twitter.com/username
      name: Twitter
    - icon: material/linkedin
      link: https://linkedin.com/in/username
      name: LinkedIn
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/473782008?spm_id_from=333.788.0.0
      name: Bilibili
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ljxrango@outlook.com> #联系方式

      name: Outlook邮箱
  # 分享功能配置（未实现）
  social_share:
    - platform: twitter
      text: 分享到 Twitter
      icon: material/twitter
    - platform: facebook
      text: 分享到 Facebook
      icon: material/facebook
    - platform: linkedin
      text: 分享到 LinkedIn
      icon: material/linkedin
    - platform: weibo
      text: 分享到微博
      icon: material/sina-weibo
  # Giscus 配置 评论系统
  # 需要overrides，未实现
    # comments:
    #   provider: giscus
    #   repo: username/repo
    #   repo_id: your_repo_id
    #   category: Comments
    #   category_id: your_category_id


  # Google Analytics 数据统计
  analytics: 
    provider: google
    property: G-XXXXXXXXXX # Google Analytics ID
    # 事件追踪
    events: true
    # 用户行为追踪
    behavior: true
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。

# 对markdown语法的扩展
markdown_extensions:
  - meta # 支持在 Markdown 文件头部添加元数据：
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 4          # 目录深度
      separator: "_"        # 标题锚点分隔符
      title: "目录"         # 目录标题
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds: {case: lower} # URL 转换规则
  - abbr
  - tables #增强的表格支持
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.snippets     # 代码片段
  - pymdownx.magiclink    # 自动链接
  - pymdownx.critic:      # 编辑标记,突出显示文档中添加、删除或更新的部分
      mode: view    #查看更改
  - pymdownx.tilde      # 删除线
  - pymdownx.mark        # ==标记==
  - pymdownx.caret      # 上标
  - pymdownx.keys       # 键盘按键
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:  # latex支持 数学公式
      generic: true
      # numbering: true #启用公式编号
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji: #添加表情符号支持
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # Mermaid 集成   图表支持
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: plantuml
        #   class: plantuml
        #   format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist: #任务列表支持
      custom_checkbox: true    # 自定义复选框样式
      clickable_checkbox: true # 可点击
  - pymdownx.tabbed    # 标签页样式
      # alternate_style: true


extra_javascript:
  - javascripts/katex.js 
  # - javascripts/tasklist.js
  # - javascripts/tabs.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://unpkg.com/mermaid@9/dist/mermaid.min.js



extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # - stylesheets/tasklist.css
  # - stylesheets/tabs.css







